#!/usr/bin/python
"""
Make a contour plot of all_ions_and_molecules.hist
generated by SDF.x
"""
import os, sys, commands, glob
import pylab, Numeric

def main():

    # Retrieve user input
    try:
        f = open(sys.argv[1],'r')
        header = f.readline()
        lines = f.readlines()
        f.close()
    except:
        print '\n usage: '+sys.argv[0]+' all_ions_and_molecules.hist\n'
        sys.exit(0)

    # Initialize arrays and counting variables
    R, THETA, SDF = [], [], []
    k = -1

    # Read in the data and format
    for line in lines:

        row = line.split()
        r = float(row[0])
        theta = float(row[1])
        sdf = float(row[2])

        if r not in R:
            R.append(r)
            SDF.append([])
            k += 1
        if theta not in THETA:
            THETA.append(theta)

        if sdf == 0.0:
            sdf = 1E-6

        SDF[k].append(sdf)

    THETA = Numeric.array(THETA)*180./Numeric.pi
    R = Numeric.array(R)*0.529177

#    print Numeric.shape(X),Numeric.shape(Y),Numeric.shape(Z)

    # Create the plot
    pylab.figure(num=1,figsize=(8,4),facecolor='w',edgecolor='k')
    pylab.contourf(THETA,R,SDF,100,antialiased=False)
    pylab.title('SDF',fontsize=14)
    pylab.xlabel('THETA',fontsize=12)
    pylab.ylabel('R',fontsize=12)
#    pylab.colorbar()

    pylab.savefig('SDF.png')
    pylab.clf()

#    pylab.show()


if __name__ == '__main__':
    main()
